### ISSUE TITLE
iOS plist文件怎么弄

### ISSUE THREAD

**Issue by wonderffee** [skytoup/AppServer#4]
fir.im和蒲公英都可以做到自动生成 plist 文件，这个好像做不好，遗憾啊，其它都能用

**Comment by skytoup** [comment]
> fir.im和蒲公英都可以做到自动生成 plist 文件，这个好像做不好，遗憾啊，其它都能用

自动生成是可以的, plistlib可以实现生成

这个也可以的, 只是可能不符合你的需求
